service: series-flix

frameworkVersion: '>=3.15.0'

plugins:
  - serverless-localstack
  - serverless-delete-loggroups

package:
  individually: true
  excludeDevDependencies: false
  include:
    - src/**
  exclude:
    - node_modules/**
    - ./**

custom:
  localstack:
    debug: true
    stages:
      - local
    endpointFile: localstack.json

  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:

  - ${file(src/handlers/http/games/routes.yml)}
