create_serie:
    handler: src/handlers/http/series/create_serie.handler
    environment:
      DYNAMODB_TABLE: series-${sls:stage}
    events:
      - http:
          method: POST
          path: /series/new